Repository stackernews/stacker.news, pull requests merged in 2023-09, with the labels that each got.

#476 Vary push notification body for subscriptions based on whether item is post
  api/resolvers/item.js
Labels: bug

#469 toast border color based on variant
  components/toast.js
  components/toast.module.css
Labels: bug

#478 Fix replying to wrong comment
  components/reply.js
Labels: bug

#483 Remove orientation from manifest
  pages/api/site.webmanifest.js
Labels: bug

#418 Add new visitor welcome banner
  api/resolvers/user.js
  api/typeDefs/user.js
  components/banners.js
  components/banners.module.css
  fragments/users.js
  pages/~/index.js
  prisma/migrations/20230829205147_welcome_banner/migration.sql
  prisma/schema.prisma
Labels: feature

#433 move search bar to top of page
  api/resolvers/item.js
  api/resolvers/search.js
  components/layout.js
  components/search.js
  components/search.module.css
  components/top-header.js
  lib/constants.js
  pages/~/search.js
Labels: enhancement

#464 Automatically subscribe forward users to threads
  prisma/migrations/20230831144120_thread_sub_forward_user/migration.sql
Labels: enhancement

#466 Visual Character counter for post titles, poll options
  components/bounty-form.js
  components/discussion-form.js
  components/form.js
  components/job-form.js
  components/link-form.js
  components/poll-form.js
Labels: feature

#467 Notifications for when you are forwarded sats from a post
  api/resolvers/item.js
  api/resolvers/notifications.js
  api/resolvers/user.js
  api/typeDefs/notifications.js
  api/typeDefs/user.js
  api/webPush/index.js
  components/notifications.js
  fragments/notifications.js
  fragments/users.js
  pages/settings.js
  prisma/migrations/20230901185713_notify_fwd_zap/migration.sql
  prisma/schema.prisma
Labels: feature

#481 Hide wallet balance
  api/typeDefs/user.js
  components/header.js
  components/hidden-wallet-summary.js
  fragments/users.js
  lib/validate.js
  pages/settings.js
  pages/wallet.js
  prisma/migrations/20230912122629_hide_wallet_balance/migration.sql
  prisma/schema.prisma
Labels: feature

#474 Verified contributors
  api/resolvers/user.js
  api/typeDefs/user.js
  components/user-header.js
  contributors.txt
  fragments/users.js
  lib/validate.js
  pages/settings.js
  prisma/migrations/20230906010648_verified_contributors/migration.sql
  prisma/schema.prisma
Labels: feature

#463 Add setting to send diagnostics back to SN
  .env.sample
  api/slack/index.js
  api/typeDefs/user.js
  components/logger.js
  components/serviceworker.js
  fragments/users.js
  lib/fancy-names.json
  lib/validate.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/log/index.js
  pages/settings.js
  prisma/migrations/20230908211455_diagnostics/migration.sql
  prisma/schema.prisma
  sw/index.js
Labels: feature

#506 Update .env.sample
  .env.sample
Labels: local dev
