Repository stackernews/stacker.news, pull requests merged in 2024-03, with the labels that each got.

#878 Territory transfers
  api/resolvers/notifications.js
  api/resolvers/sub.js
  api/typeDefs/notifications.js
  api/typeDefs/sub.js
  components/notifications.js
  components/territory-header.js
  components/territory-transfer.js
  fragments/notifications.js
  lib/push-notifications.js
  lib/validate.js
  prisma/migrations/20240305143404_territory_transfer/migration.sql
  prisma/schema.prisma
  sw/eventListener.js
Labels: feature

#895 Fix alignment of info icon
  components/info.js
Labels: bug

#902 Parse numeric strings as numbers
  components/form.js
Labels: bug

#906 Fix zap shadow on hover
  components/upvote.js
Labels: bug

#912 Add security.txt
  public/.well-known/security.txt
  public/pgp.txt
Labels: admin

#909 Fix image fees undefined and not enforced if logged in
  api/resolvers/image.js
  api/resolvers/item.js
Labels: bug

#905 Don't hide self in top even if hidden
  api/resolvers/user.js
  components/user-header.module.css
  components/user-list.js
Labels: enhancement, privacy, ux

#904 Ignore if sub belongs to user during existence check
  api/resolvers/sub.js
  components/territory-form.js
  lib/validate.js
Labels: bug

#915 API Keys
  api/resolvers/user.js
  api/typeDefs/user.js
  components/discussion-form.js
  fragments/users.js
  pages/api/graphql.js
  pages/settings/index.js
  prisma/migrations/20240312111708_api_keys/migration.sql
  prisma/schema.prisma
  svgs/delete-bin-line.svg
Labels: feature

#931 Fix ToC due to repeated slug calls
  components/text.js
Labels: bug

#930 Don't filter by pins in home
  api/resolvers/item.js
Labels: bug

#929 Add setting for no referral links on copy
  api/typeDefs/user.js
  components/share.js
  fragments/users.js
  lib/validate.js
  pages/settings/index.js
  prisma/migrations/20240317144736_referral_link_privacy_setting/migration.sql
  prisma/schema.prisma
Labels: feature, privacy

#940 Fix duplicate deposit push messages sent
  prisma/migrations/20240319153857_create_invoice_return_success/migration.sql
  worker/wallet.js
Labels: bug

#935 Fix container with empty name not found
  sndev
Labels: bug

#897 Purchase archived territories
  api/resolvers/sub.js
  api/typeDefs/sub.js
  components/form.js
  components/territory-form.js
  lib/validate.js
Labels: feature

#946 Fix territory transfer push notification sent to everyone
  api/resolvers/sub.js
Labels: bug

#952 Fix timing between billedLastAt and billPaidUntil
  api/resolvers/sub.js
Labels: bug

#949 Check userId set in sendUserNotification
  lib/webPush.js
Labels: bug

#968 Keep standard ports inside container
  docker-compose.yml
Labels: local dev

#971 Withdrawal notifications
  api/resolvers/notifications.js
  api/resolvers/user.js
  api/resolvers/wallet.js
  api/typeDefs/notifications.js
  api/typeDefs/user.js
  components/notifications.js
  fragments/notifications.js
  fragments/users.js
  lib/webPush.js
  pages/settings/index.js
  prisma/migrations/20240325114003_withdrawal_notifications/migration.sql
  prisma/schema.prisma
  sw/eventListener.js
  worker/wallet.js
Labels: feature

#973 Fix zap undo wrong default value shown
  pages/settings/index.js
Labels: bug

#980 Hash API keys with SHA-256 before storing them
  api/resolvers/user.js
  api/typeDefs/user.js
  components/modal.js
  pages/api/graphql.js
  pages/settings/index.js
  prisma/migrations/20240326181608_api_key_sha256/migration.sql
  prisma/schema.prisma
  styles/globals.scss
Labels: enhancement, difficulty:medium

#982 Improved navigation with dedicated mobile navigation
  api/resolvers/search.js
  api/ssrApollo.js
  components/fee-button.js
  components/footer.js
  components/hat.js
  components/header.js
  components/header.module.css
  components/hidden-wallet-summary.js
  components/item.module.css
  components/layout.js
  components/layout.module.css
  components/nav/common.js
  components/nav/desktop/header.js
  components/nav/desktop/second-bar.js
  components/nav/desktop/top-bar.js
  components/nav/index.js
  components/nav/mobile/footer.js
  components/nav/mobile/footer.module.css
  components/nav/mobile/header.js
  components/nav/mobile/offcanvas.js
  components/nav/mobile/second-bar.js
  components/nav/mobile/top-bar.js
  components/nav/static.js
  components/nav/sticky-bar.js
  components/post.js
  components/recent-header.js
  components/search.js
  components/search.module.css
  components/sub-select.js
  components/sub-select.module.css
  components/territory-header.js
  components/top-header.js
  components/use-has-new-notes.js
  fragments/users.js
  middleware.js
  next.config.js
  package-lock.json
  package.json
  pages/[name]/index.js
  pages/_app.js
  pages/_document.js
  pages/invites/[id].js
  pages/items/[id]/edit.js
  pages/login.js
  pages/search.js
  pages/signup.js
  pages/~/index.js
  styles/globals.scss
  styles/search.module.css
  svgs/sn.svg
Labels: difficulty:hard

#985 Fix alignment in modal
  components/modal.js
  styles/globals.scss
Labels: bug

#998 Fix CSP commented out in middleware
  middleware.js
Labels: bug

#997 Fix QR scanner collapsed to no width
  styles/globals.scss
Labels: bug
