Repository stackernews/stacker.news, pull requests merged in 2024-04, with the labels that each got.

#994 Wallet Logs
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/log-message.js
  components/log-message.module.css
  components/logger.js
  components/serviceworker.js
  components/wallet-logs.js
  components/webln/lnbits.js
  components/webln/nwc.js
  fragments/wallet.js
  pages/settings/index.js
  pages/settings/wallets/lightning-address.js
  pages/settings/wallets/lnbits.js
  pages/settings/wallets/lnd.js
  pages/settings/wallets/nwc.js
  pages/wallet/index.js
  pages/wallet/logs.js
  prisma/migrations/20240403013755_wallet_logs/migration.sql
  prisma/schema.prisma
  styles/log.module.css
  worker/autowithdraw.js
Labels: feature

#1013 Never notify on replies from self
  api/resolvers/notifications.js
Labels: bug

#1014 Remove useRef for NWC relay
  components/webln/nwc.js
Labels: enhancement

#1019 Fix effect dependencies
  components/logger.js
  components/webln/nwc.js
Labels: bug

#1027 Add missing space in front of founding date
  components/territory-header.js
Labels: bug

#1029 Fix 404 for territories in profile
  api/resolvers/sub.js
Labels: bug

#1031 fix: feetext defaults to free
  components/fee-button.js
Labels: bug

#1052 Fix LND autowithdrawal error message
  worker/autowithdraw.js
Labels: bug

#1057 Fix cert required
  lib/validate.js
Labels: bug

#1042 CLN autowithdrawal
  .env.sample
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/log-message.js
  components/logger.js
  docker-compose.yml
  docker/cln/Dockerfile
  docker/cln/ca-key.pem
  docker/cln/ca.pem
  docker/cln/ca.srl
  docker/cln/client-key.pem
  docker/cln/client.csr
  docker/cln/client.pem
  docker/cln/hsm_secret
  docker/cln/server-key.pem
  docker/cln/server.csr
  docker/cln/server.pem
  fragments/wallet.js
  lib/cln.js
  lib/validate.js
  package-lock.json
  package.json
  pages/settings/wallets/cln.js
  pages/settings/wallets/index.js
  prisma/migrations/20240410060146_wallet_cln/migration.sql
  prisma/schema.prisma
  sndev
  worker/autowithdraw.js
Labels: feature

#1072 Fix TypeError if autowithdrawal creation failed
  worker/autowithdraw.js
Labels: bug

#1078 Add autowithdrawal badge in notifications
  api/resolvers/notifications.js
  api/resolvers/wallet.js
  api/typeDefs/notifications.js
  components/notifications.js
  components/notifications.module.css
  fragments/notifications.js
Labels: enhancement, ux

#1073 Fix autowithdrawal logs
  api/resolvers/wallet.js
  components/logger.js
  prisma/migrations/20240415113539_withdrawal_wallet_id/migration.sql
  prisma/schema.prisma
  worker/autowithdraw.js
  worker/wallet.js
Labels: bug

#1083 Fix TypeError: Failed to construct 'URL': Invalid URL
  components/text.js
Labels: bug

#1103 Support LNURL-verify
  pages/api/lnurlp/[username]/pay.js
  pages/api/lnurlp/[username]/verify/[hash].js
Labels: feature

#1106 Show preimage of confirmed withdrawals
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  fragments/wallet.js
  pages/withdrawals/[id].js
Labels: feature

#1120 Use njump.me for nostr links
  components/footer.js
  components/item-info.js
  components/notifications.js
  components/user-header.js
Labels: nostr

#1122 Fix missing logger.error and setStatus
  components/webln/lnbits.js
  components/webln/lnc.js
  components/webln/nwc.js
Labels: bug, wallets

#1121 Fix duplicate autowithdrawal logs
  prisma/migrations/20240429_224542_reverse_withdrawal_return_value/migration.sql
  worker/wallet.js
Labels: bug, wallets
