Repository stackernews/stacker.news, pull requests merged in 2024-08, with the labels that each got.

#1282 More zap undo fixes IV
  components/item-act.js
  components/upvote.js
  pages/settings/index.js
Labels: bug

#1284 Only validate tipRandom if enabled
  lib/validate.js
  pages/settings/index.js
Labels: bug, ux

#1285 Crosspost errors are warnings now
  components/use-crossposter.js
Labels: ux

#1292 Fix callback set to NextJS data URL
  api/ssrApollo.js
Labels: bug

#1289 fix: constrain less important services in docker compose
  .env.development
  docker-compose.yml
Labels: local dev, difficulty:easy

#1278 Support receiving via LNbits
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/autowithdraw-shared.js
  components/wallet-logger.js
  docker-compose.yml
  docs/attach-lnbits.md
  fragments/wallet.js
  lib/validate.js
  pages/settings/wallets/[wallet].js
  prisma/migrations/20240729195320_lnbits_recv/migration.sql
  prisma/schema.prisma
  wallets/index.js
  wallets/lnbits/ATTACH.md
  wallets/lnbits/client.js
  wallets/lnbits/index.js
  wallets/lnbits/server.js
  wallets/server.js
Labels: feature, wallets

#1295 Add migration to fix missing item bio marker
  prisma/migrations/20240812234244_update_bio_marker/migration.sql
Labels: bug

#1298 Fix freebie comment edits like a post
  api/resolvers/item.js
Labels: bug

#1299 Fix WebLN checkbox unclickable
  components/use-local-state.js
  pages/settings/wallets/[wallet].js
  wallets/index.js
Labels: bug

#1308 Fix all wallets deleted on logout
  wallets/index.js
Labels: bug

#1309 Generate more server wallet code
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  fragments/wallet.js
  lib/wallet.js
Labels: wallets

#1313 Add wasm-unsafe-eval to CSP for LNC
  middleware.js
Labels: bug

#1302 Use custom relay API
  components/nostr-auth.js
  components/use-crossposter.js
  lib/nostr.js
  lib/time.js
  package-lock.json
  package.json
  wallets/nwc/client.js
  worker/nostr.js
Labels: enhancement, nostr

#1318 Fix inconsistency between walletTypeToResolveType and generateTypeDefName
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  lib/wallet.js
Labels: bug

#1319 Fix missing fragment name update
  fragments/wallet.js
Labels: bug

#1321 Rename LNbits primary key column from 'int' to 'id'
  prisma/migrations/20240821072645_rename_lnbits_pk/migration.sql
  prisma/schema.prisma
Labels: bug

#1325 Show item details via context menu
  api/typeDefs/item.js
  components/item-info.js
  components/item.module.css
  fragments/items.js
Labels: feature

#1328 Rename NWC primary key column from 'int' to 'id'
  prisma/migrations/20240823045403_rename_nwc_pk/migration.sql
  prisma/schema.prisma
Labels: bug

#1330 Fix cost not shown in comment details
  fragments/comments.js
Labels: bug

#1329 Fix full config saved on client on priority change
  wallets/index.js
Labels: bug

#1322 Phoenixd send+recv
  fragments/wallet.js
  lib/validate.js
  prisma/migrations/20240821014115_phoenixd/migration.sql
  prisma/schema.prisma
  scripts/genwallet.sh
  wallets/client.js
  wallets/phoenixd/client.js
  wallets/phoenixd/index.js
  wallets/phoenixd/server.js
  wallets/server.js
Labels: feature, wallets

#1337 Fix preimage undefined in wallet logs
  wallets/README.md
  wallets/blink/client.js
  wallets/index.js
  wallets/lnbits/client.js
  wallets/lnc/client.js
  wallets/phoenixd/client.js
Labels: bug, wallets

#1335 NWC hardcoded keys
  docker/nwc/Dockerfile
  docker/nwc/keys.json
  wallets/nwc/ATTACH.md
Labels: wallets

#1334 Fix websocket leaks
  lib/nostr.js
  worker/nostr.js
Labels: bug

#1336 Support Tor for LNbits recv
  lib/cln.js
  lib/proxy.js
  wallets/lnbits/server.js
Labels: wallets

#1338 Update wallet security banner
  components/banners.js
  pages/settings/wallets/[wallet].js
Labels: wallets

#1339 Add a.stacker.news to script-src
  middleware.js
Labels: bug
