Repository stackernews/stacker.news, pull requests merged in 2024-01, with the labels that each got.

#729 Only close notifications manually on iOS
  components/logger.js
  components/serviceworker.js
  sw/eventListener.js
Labels: bug

#730 Fix usage of hardcoded strings for sw message types
  components/serviceworker.js
  sw/eventListener.js
Labels: documentation

#731 Refactor delete notification code
  components/bounty-form.js
  components/comment-edit.js
  components/discussion-form.js
  components/job-form.js
  components/link-form.js
  components/poll-form.js
  components/reply.js
  lib/form.js
Labels: bug

#732 Fix invalid DOM property
  pages/wallet.js
Labels: bug

#726 Use LND subscriptions
  README.md
  api/resolvers/serial.js
  api/resolvers/wallet.js
  lib/constants.js
  pages/api/lnurlp/[username]/pay.js
  prisma/migrations/20240104004135_invoice_confirmed_index/migration.sql
  prisma/migrations/20240105190205_replace_polling_with_lnd_subscriptions/migration.sql
  prisma/schema.prisma
  worker/index.js
  worker/wallet.js
Labels: enhancement

#739 Fix push notification counting on iOS devices
  sw/eventListener.js
Labels: bug

#742 Fix TypeError (reading 'catch')
  pages/api/log/index.js
Labels: bug

#744 Fix TypeError on item creation if JIT invoicing is used
  api/resolvers/serial.js
Labels: bug

#745 Territory post notifications
  api/resolvers/item.js
  api/resolvers/notifications.js
  api/typeDefs/notifications.js
  api/typeDefs/user.js
  api/webPush/index.js
  components/notifications.js
  fragments/notifications.js
  fragments/users.js
  lib/push-notifications.js
  pages/settings.js
  prisma/migrations/20240110195551_territory_posts_notifications/migration.sql
  prisma/schema.prisma
  sw/eventListener.js
Labels: feature

#750 Fix 'column Item.day does not exist'
  api/resolvers/user.js
Labels: bug

#751 Fix logged title
  sw/eventListener.js
Labels: bug

#755 Unified QR scanning
  pages/wallet.js
Labels: feature

#764 Fix stale confirmedIndex used on reconnect
  worker/wallet.js
Labels: bug

#766 Fix typo in FILTER for posts in user stats
  prisma/migrations/20240124000131_fix_user_stats_post/migration.sql
Labels: bug

#765 Format internal links as #<id>
  components/text.js
Labels: feature

#769 Fix image deletion batch size
  api/s3/index.js
  worker/deleteUnusedImages.js
Labels: bug

#767 Allow territory founders to pin items
  api/resolvers/item.js
  api/typeDefs/item.js
  components/comment.js
  components/comment.module.css
  components/comments.js
  components/item-info.js
  components/item.module.css
  components/items.js
  components/territory-header.js
  fragments/comments.js
  prisma/migrations/20240130165240_existing_pins_null_sub/migration.sql
Labels: feature
