Repository stackernews/stacker.news, pull requests merged in 2024-11, with the labels that each got.

#1506 Color send & recv badges
  components/wallet-card.js
  styles/wallet.module.css
  wallets/blink/index.js
  wallets/cln/index.js
  wallets/lightning-address/index.js
  wallets/lnbits/index.js
  wallets/lnc/index.js
  wallets/lnd/index.js
  wallets/nwc/index.js
  wallets/phoenixd/index.js
  wallets/webln/index.js
Labels: enhancement, wallets

#1513 Fix description of wrapped invoices don't respect privacy setting
  api/paidAction/index.js
  wallets/wrap.js
Labels: bug, wallets

#1520 Don't hide cancel if edit timer runs out
  components/comment.js
  components/item-info.js
Labels: ux

#1479 Blink Receive
  fragments/wallet.js
  lib/validate.js
  pages/settings/wallets/[wallet].js
  prisma/migrations/20241016171557_blinkreceive/migration.sql
  prisma/schema.prisma
  wallets/blink/client.js
  wallets/blink/common.js
  wallets/blink/index.js
  wallets/blink/server.js
  wallets/server.js
Labels: feature, wallets

#1512 Fix some issues in clear button for input fields
  components/form.js
Labels: bug, wallets

#1527 Prevent UPDATE_COMMENT from invalidating the cache of child comments (Fix #1509 )
  fragments/paidAction.js
Labels: bug

#1528 decode minified stacktrace
  components/error-boundary.js
  lib/stacktrace.js
  package-lock.json
  package.json
Labels: feature

#1536 Fix wallet priority reorder inconsistency
  pages/settings/wallets/index.js
Labels: bug, wallets

#1535 Fix global wallet logs never fetch logs from server
  components/wallet-logger.js
Labels: bug, wallets

#1516 supercharged wallet logs
  api/paidAction/index.js
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/log-message.js
  components/log-message.module.css
  components/use-interval.js
  components/wallet-logger.js
  fragments/wallet.js
  lib/cln.js
  lib/fetch.js
  lib/format.js
  lib/url.js
  prisma/migrations/20241105021205_log_context/migration.sql
  prisma/schema.prisma
  styles/log.module.css
  wallets/blink/server.js
  wallets/index.js
  wallets/lnbits/client.js
  wallets/lnbits/server.js
  wallets/lnc/client.js
  wallets/nwc/index.js
  wallets/nwc/server.js
  wallets/phoenixd/client.js
  wallets/phoenixd/server.js
  wallets/server.js
  worker/autowithdraw.js
  worker/paidAction.js
  worker/wallet.js
Labels: enhancement, wallets

#1562 Only send push notification if referrer was updated
  pages/api/auth/[...nextauth].js
Labels: bug

#1561 Fix offcanvas not closed before showing logout prompt
  components/nav/common.js
Labels: bug

#1571 Fix edit countdown on deleted items
  api/resolvers/item.js
  components/item-info.js
Labels: bug

#1565 Fix outlawed can show up on front page
  api/resolvers/item.js
Labels: bug

#1581 Fix missing sorting of wallet logs
  components/wallet-logger.js
Labels: bug, wallets

#1582 Fix fee added to received amount
  worker/paidAction.js
  worker/wallet.js
Labels: bug, wallets

#1594 Fix TypeError if local storage is cleared
  wallets/index.js
Labels: bug

#1595 Fix unpaid items are counted
  api/resolvers/user.js
Labels: bug

#1597 Fix #undefined in downzap invoice description
  api/paidAction/downZap.js
Labels: bug

#1583 fix: upvote widget not rendered when comment is collapsed
  components/comment.js
  components/upvote.js
Labels: bug

#1585 fix: reply storage is updated with the new content on file upload
  components/form.js
Labels: bug

#1603 Fix missing useDarkMode update
  components/dark-mode.js
Labels: bug

#1559 Wallet send+recv status derived from logs
  api/resolvers/wallet.js
  components/log-message.js
  components/wallet-buttonbar.js
  components/wallet-card.js
  components/wallet-logger.js
  pages/settings/wallets/[wallet].js
  public/wallets/blink-dark.svg
  public/wallets/blink.svg
  public/wallets/cln-dark.svg
  public/wallets/cln.svg
  public/wallets/lnbits-dark.svg
  public/wallets/lnbits.svg
  public/wallets/lnd-dark.png
  public/wallets/lnd.png
  public/wallets/phoenixd-dark.png
  public/wallets/phoenixd.png
  scripts/genwallet.sh
  styles/wallet.module.css
  svgs/arrow-left-down-line.svg
  svgs/arrow-right-up-line.svg
  wallets/README.md
  wallets/blink/index.js
  wallets/cln/index.js
  wallets/common.js
  wallets/config.js
  wallets/index.js
  wallets/lightning-address/index.js
  wallets/lnbits/index.js
  wallets/lnc/client.js
  wallets/lnc/index.js
  wallets/lnd/index.js
  wallets/nwc/index.js
  wallets/phoenixd/index.js
  wallets/webln/index.js
Labels: feature, wallets

#1609 Fix 'Cannot mix BigInt and other types' on zaps
  api/paidAction/index.js
  api/paidAction/receive.js
  worker/paidAction.js
Labels: bug

#1615 Fix mentions for pessimistic actions
  api/paidAction/lib/item.js
  worker/paidAction.js
Labels: bug

#1618 Fix account switching anon login
  pages/api/auth/[...nextauth].js
  pages/api/graphql.js
Labels: bug

#1624 Fix wallet status ignoring failed requests to create invoices
  wallets/server.js
Labels: bug

#1626 Fix lnaddr not returning payment request
  wallets/lightning-address/server.js
Labels: bug

#1631 Use invoice.cancelledAt to determine if invoice expired or was canceled by user
  api/typeDefs/wallet.js
  components/countdown.js
  components/invoice.js
  components/payment.js
  fragments/wallet.js
  prisma/migrations/20241122041724_invoice_cancelled_at/migration.sql
  prisma/schema.prisma
  worker/paidAction.js
  worker/wallet.js
Labels: bug

#1641 Remove unused function usePayment
  components/payment.js
Labels: wallets

#1640 refactor: Check darkmode in useWallets
  components/wallet-card.js
  components/wallet-image.js
  pages/settings/wallets/[wallet].js
Labels: wallets

#1638 Only fetch logs when we need them
  components/use-interval.js
  components/wallet-logger.js
Labels: bug, wallets

#1646 More wallet hooks: useWalletStatus & useWalletSupport
  components/wallet-card.js
  components/wallet-status.js
  components/wallet-support.js
  wallets/common.js
  wallets/index.js
Labels: wallets

#1651 Fix actionArgs of new invoice during retry
  api/paidAction/index.js
Labels: bug

#1660 Remove unused useWallet from QR code component
  components/invoice.js
  components/payment.js
  components/qr.js
  pages/invoices/[id].js
Labels: wallets

#1662 Fix deposit push notifications
  lib/webPush.js
Labels: bug

#1642 Sender fallbacks
  api/paidAction/index.js
  components/invoice.js
  components/item-act.js
  components/notifications.js
  components/payment.js
  components/use-paid-mutation.js
  components/wallet-logger.js
  fragments/wallet.js
  wallets/common.js
  wallets/config.js
  wallets/errors.js
  wallets/index.js
  wallets/lnc/client.js
  wallets/logger.js
  wallets/payment.js
Labels: feature, wallets

#1589 feat: recent unpaid bounties selection
  api/resolvers/item.js
  components/recent-header.js
  pages/~/recent/[type].js
Labels: feature

#1666 Fix missing authentication check for invite revocation
  api/resolvers/invite.js
  components/invite.js
Labels: bug
