Repository stackernews/stacker.news, pull requests merged in 2024-12, with the labels that each got.

#1649 Custom invite code and note
  api/resolvers/invite.js
  api/typeDefs/invite.js
  components/invite.js
  components/notifications.js
  components/reply.js
  fragments/invites.js
  lib/validate.js
  pages/invites/index.js
  prisma/migrations/20241125195641_custom_invites/migration.sql
  prisma/schema.prisma
Labels: feature

#1684 Fix wallet logs delete for single wallet
  components/wallet-logger.js
Labels: bug

#1698 Use same naming scheme between ln containers and env vars
  .env.development
  docker-compose.yml
Labels: sndev

#1701 CLN: Use port 9735 and log to stdout
  docker-compose.yml
Labels: sndev

#1700 Use new LND node as routing node
  .env.development
  docker-compose.yml
  docker/lnd/router/regtest/admin.macaroon
  docker/lnd/router/regtest/macaroons.db
  docker/lnd/router/regtest/wallet.db
  docker/lnd/router/tls.cert
  docker/lnd/router/tls.key
  scripts/test-routing.sh
Labels: sndev

#1688 Receiver fallbacks
  api/paidAction/index.js
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/use-invoice.js
  fragments/wallet.js
  prisma/migrations/20241206155927_invoice_predecessors/migration.sql
  prisma/schema.prisma
  wallets/errors.js
  wallets/payment.js
  wallets/server.js
Labels: feature, wallets

#1705 Fix latest timestamp not updated
  components/wallet-logger.js
Labels: bug, wallets

#1713 Use same view about failed forwards on server and client
  wallets/server.js
Labels: wallets

#1709 Fix pending forwards considered paid by client
  components/item-act.js
  components/use-invoice.js
Labels: bug, wallets

#1714 Don't expose p2p zap receivers to routing fees
  components/notifications.js
  worker/paidAction.js
Labels: bug, wallets

#1716 Fix forever edits
  api/resolvers/item.js
  components/use-can-edit.js
  lib/constants.js
  lib/item.js
Labels: bug

#1719 Fix missing logging of sender wallet validation error
  wallets/config.js
Labels: bug, wallets

#1720 Fix missing toast padding
  components/toast.js
Labels: bug

#1590 NDK
  components/use-crossposter.js
  lib/nostr.js
  lib/url.js
  lib/yup.js
  package-lock.json
  package.json
  wallets/nwc/client.js
  wallets/nwc/index.js
  wallets/nwc/server.js
  worker/index.js
  worker/nostr.js
Labels: enhancement

#1723 Fix receiver fallbacks depend on fast polls
  wallets/payment.js
Labels: bug, wallets

#1636 Nip46 auth with NDK
  .env.development
  components/lightning-auth.js
  components/nostr-auth.js
  lib/nostr.js
Labels: auth

#1724 Remove unused wallet context args
  api/resolvers/wallet.js
  wallets/config.js
  wallets/nwc/client.js
  wallets/nwc/index.js
  wallets/nwc/server.js
Labels: wallets

#1725 Refactor Blink function signatures
  wallets/blink/client.js
  wallets/blink/common.js
  wallets/blink/server.js
Labels: wallets

#1726 Refactor CLN function signatures
  lib/cln.js
  wallets/cln/server.js
Labels: wallets

#1728 Fix lightning address logs deletion
  components/wallet-logger.js
Labels: bug, wallets

#1722 Add timeouts to all wallet API calls
  api/resolvers/wallet.js
  lib/cln.js
  lib/constants.js
  lib/fetch.js
  lib/lnurl.js
  lib/time.js
  wallets/blink/client.js
  wallets/blink/common.js
  wallets/blink/server.js
  wallets/cln/server.js
  wallets/config.js
  wallets/lightning-address/server.js
  wallets/lnbits/client.js
  wallets/lnbits/server.js
  wallets/nwc/client.js
  wallets/nwc/index.js
  wallets/nwc/server.js
  wallets/payment.js
  wallets/phoenixd/client.js
  wallets/phoenixd/server.js
  wallets/server.js
Labels: enhancement, wallets

#1729 Fix missing logs on save
  api/resolvers/wallet.js
  wallets/config.js
Labels: bug, wallets

#1737 Fix admin edits
  api/resolvers/item.js
Labels: bug

#1732 Fix send-only wallet save after device sync enabled
  api/resolvers/wallet.js
Labels: bug, wallets

#1752 update cache on vault key update
  components/vault/use-vault-configurator.js
Labels: bug, wallets

#1753 Fix upvote button shown for deleted items
  components/boost-button.js
  components/upvote.module.css
Labels: bug

#1765 Fix typo in deposit notification
  components/notifications.js
Labels: bug

#1748 Require invite limit
  api/paidAction/inviteGift.js
  api/typeDefs/invite.js
  pages/invites/index.js
Labels: bug

#1747 Add exclusion constraint to prevent duplicate items within 10m
  api/paidAction/itemCreate.js
  prisma/migrations/20241220000308_fix_duplicate_comments/migration.sql
Labels: bug

#1773 Fix user since if first item wasn't paid
  api/resolvers/user.js
Labels: bug

#1780 filter out POST /api/graphql spam from sndev logs
  sndev
Labels: sndev

#1782 Fix NostrAuth link text
  pages/settings/index.js
Labels: bug, auth

#1775 Fix muted parents not uncollapsed
  components/comment.js
Labels: bug, ux

#1783 Always return new user token for JWT callback to use
  pages/api/auth/[...nextauth].js
Labels: bug, auth
