Repository stackernews/stacker.news, pull requests merged in 2025-03, with the labels that each got.

#1913 Redirect to top cowboys page if there's a time descriptor
  next.config.js
  pages/~/top/cowboys.js
Labels: bug

#1858 fix: WebLN QR fallback for anon users
  components/use-qr-payment.js
  wallets/errors.js
  wallets/payment.js
  wallets/webln/client.js
Labels: bug

#1940 Fix footnotes and overflow
  components/text.js
Labels: bug

#1944 Fix undefined db for wallet logs
  wallets/payment.js
Labels: bug, wallets

#1960 Fix fetching of user items in welcome script
  scripts/welcome.js
Labels: bug

#1963 Fix item cost in details
  api/paidAction/itemCreate.js
  fragments/items.js
Labels: bug

#1969 Fix saloon replies
  api/paidAction/itemCreate.js
Labels: bug

#1971 Don't poll failed invoices if anon
  wallets/index.js
Labels: bug

#1977 Fix @remindme does not support weeks
  lib/time.js
Labels: bug, bot

#1987 Fix warning about missing key for children
  components/login.js
Labels: bug

#1986 Hide pull-to-refresh when not pulling
  components/pull-to-refresh.js
Labels: bug

#1953 Fix no pw manager autofill for device sync password
  pages/settings/passphrase/index.js
Labels: bug, ux, wallets

#1976 Prevent new account creation on login
  components/login.js
  pages/api/auth/[...nextauth].js
  pages/login.js
Labels: ux, auth

#1957 Reset multi_auth cookies on error
  components/account.js
  components/banners.js
  lib/auth.js
  pages/api/auth/[...nextauth].js
  pages/api/graphql.js
Labels: bug, auth

#1999 don't send a verification email during sign in if no match
  pages/api/auth/[...nextauth].js
  pages/email.js
Labels: ui/ux, auth

#2005 Use cookieOptions for pointer cookie
  components/account.js
  lib/auth.js
Labels: auth

#2006 Remove unnecessary exports
  lib/auth.js
Labels: auth

#1998 Use __Secure- cookie prefix
  api/ssrApollo.js
  components/account.js
  lib/auth.js
  pages/api/next-account.js
  pages/login.js
Labels: enhancement, auth

#1826 normalized wallet logs
  api/resolvers/wallet.js
  components/wallet-logger.js
  prisma/migrations/20250118192921_normalized_wallet_logs/migration.sql
  prisma/schema.prisma
  wallets/server.js
  worker/paidAction.js
  worker/payingAction.js
Labels: wallets

#2003 Refactor login cookie with cookieOptions function
  components/login.js
Labels: auth

#2018 Remove multi auth error checking
  components/account.js
  components/banners.js
Labels: auth

#2021 Reset if pointer is not a number or JWT cannot be decoded
  lib/auth.js
Labels: auth

#2020 Use MULTI_AUTH_REGEXP to test for multi auth keys
  lib/auth.js
Labels: auth

#2019 Refactor multi auth client-side code with new useCookie hook
  components/account.js
  components/nav/common.js
  components/use-cookie.js
  pages/_app.js
Labels: auth

#2025 Update FAQ (personalized feeds, guides)
  docs/user/faq.md
Labels: documentation

#2007 Reset multi_auth to initial state on error
  lib/auth.js
Labels: auth

#2026 Refactor reminder push notifications
  components/notifications.js
  lib/webPush.js
  worker/reminder.js
Labels: ui/ux

#2027 Merge follow-up replies with normal replies
  lib/webPush.js
  sw/eventListener.js
Labels: ui/ux

#2034 Fix wallet priority in FAQ
  docs/user/faq.md
Labels: bug, documentation

#2045 Include name in mention push notification
  api/paidAction/itemUpdate.js
  lib/webPush.js
Labels: ui/ux

#2044 Add territory link in post form info
  components/post.js
  components/territory-header.js
Labels: territories, ui/ux
