Repository stackernews/stacker.news, pull requests merged in 2025-02, with the labels that each got.

#1818 Login with magic code
  components/form.js
  components/login.js
  lib/constants.js
  lib/validate.js
  pages/api/auth/[...nextauth].js
  pages/auth/error.js
  pages/email.js
  pages/settings/index.js
  prisma/migrations/20250116091054_auth_token_attempts/migration.sql
  prisma/schema.prisma
Labels: bug, auth

#1857 Update price button accessibility in header
  components/price.js
  styles/globals.scss
Labels: difficulty:easy, accessibility

#1800 Update FAQ
  docs/user/faq.md
Labels: documentation

#1768 feat: comment fee control
  api/paidAction/itemCreate.js
  api/typeDefs/sub.js
  components/reply.js
  components/territory-form.js
  components/territory-header.js
  fragments/items.js
  fragments/paidAction.js
  fragments/subs.js
  lib/validate.js
  prisma/migrations/20241227132729_comment_fee_control/migration.sql
  prisma/schema.prisma
Labels: feature

#1887 Add territory stats answer to FAQ
  docs/user/faq.md
Labels: documentation

#1892 Fix bios missed in welcome script
  scripts/welcome.js
Labels: bug

#1893 Fix NaN in welcome script
  scripts/welcome.js
Labels: bug

#1862 enhance: referral notifications with source
  api/resolvers/notifications.js
  api/typeDefs/notifications.js
  components/notifications.js
  fragments/notifications.js
  middleware.js
  pages/api/auth/[...nextauth].js
  prisma/migrations/20250207171157_record_referee_landing/migration.sql
  prisma/schema.prisma
  worker/earn.js
Labels: enhancement

#1902 Fix comment not outlined again
  components/comment.js
Labels: bug

#1899 Don't parse content in code blocks
  lib/rehype-sn.js
Labels: bug

#1906 Fix missing cleanup of dark mode listeners
  components/dark-mode.js
Labels: bug

#1776 Automated retries
  api/paidAction/index.js
  api/resolvers/notifications.js
  api/resolvers/paidAction.js
  api/resolvers/user.js
  api/resolvers/wallet.js
  api/typeDefs/paidAction.js
  api/typeDefs/wallet.js
  components/use-invoice.js
  fragments/paidAction.js
  fragments/wallet.js
  lib/apollo.js
  lib/constants.js
  prisma/migrations/20250107084543_automated_retries/migration.sql
  prisma/schema.prisma
  wallets/index.js
  wallets/payment.js
  wallets/server.js
Labels: feature, wallets

#1907 Fix receiver fallback on caller error
  api/paidAction/index.js
  wallets/server.js
  worker/autowithdraw.js
Labels: bug, wallets

#1908 Fix autowithdrawal error handling
  worker/autowithdraw.js
Labels: bug, wallets

#1910 Dynamically import MathJax
  components/text.js
Labels: enhancement, performance
