Repository stackernews/stacker.news, pull requests merged in 2025-05, with the labels that each got.

#2149 Fix 0 sat lnaddr invoices
  wallets/lightning-address/server.js
Labels: bug, wallets

#2148 Remove 'originally posted at'
  components/use-crossposter.js
Labels: nostr

#2072 Clean opensearch final
  api/resolvers/search.js
  docker-compose.yml
Labels: blocked

#2163 Delete duplicate wallets
  prisma/migrations/20250513212337_delete_duplicate_wallets/migration.sql
  prisma/schema.prisma
Labels: bug, wallets

#2135 Exact search
  api/resolvers/search.js
  docker/opensearch/init-opensearch.sh
  scripts/nlp-setup
Labels: blocked

#2092 Migrate vault entries to new schema
  api/resolvers/vault.js
  api/resolvers/wallet.js
  prisma/migrations/20250411012334_vault_refactor/migration.sql
  prisma/schema.prisma
  wallets/vault.js
  worker/wallet.js
Labels: wallets

#2179 sn_lnd: Fix self-signed certificate error
  .env.development
  docker/lnd/sn/regtest/admin.macaroon
  docker/lnd/sn/regtest/macaroons.db
  docker/lnd/sn/regtest/wallet.db
  docker/lnd/sn/tls.cert
  docker/lnd/sn/tls.key
Labels: bug, sndev
