Repository stackernews/stacker.news, pull requests merged in 2025-08, with the labels that each got.

#2389 Fix input type of url for NWC receive
  wallets/lib/protocols/nwc.js
Labels: bug, wallets

#2382 improvements to upload fees code
  api/paidAction/itemUpdate.js
  api/paidAction/territoryUpdate.js
  api/resolvers/upload.js
Labels: refactor

#2384 Rename mutation to UPSERT_WALLET_RECEIVE_LND_GRPC
  wallets/client/fragments/protocol.js
  wallets/client/hooks/query.js
Labels: wallets, refactor

#2387 Fix link to dust limit settings in CCInfo
  components/info/cc.js
Labels: bug, wallets

#2388 Fix autoWithdraw settings schema
  lib/validate.js
Labels: wallets, refactor

#2395 Remove unused keyCheck hook
  wallets/client/context/hooks.js
  wallets/client/context/provider.js
Labels: wallets

#2396 Fix protocolId missing as dependency
  wallets/client/hooks/logger.js
Labels: bug, wallets

#2402 /wallets/debug: fix getDate is not a function
  wallets/client/components/debug.js
Labels: bug, wallets

#2355 live comments: auto show new comments
  api/typeDefs/item.js
  components/comment.js
  components/comment.module.css
  components/comments.js
  components/nav/common.js
  components/preserve-scroll.js
  components/show-new-comments.js
  components/use-live-comments.js
  fragments/comments.js
  fragments/items.js
  lib/apollo.js
  lib/comments.js
Labels: enhancement, ui/ux

#2412 Fix GraphQL cannot represent bigint as integer
  api/resolvers/upload.js
Labels: bug, multimedia

#2397 Use SSR for wallets
  pages/wallets/[...slug].js
  wallets/client/components/card.js
  wallets/client/components/forms.js
  wallets/client/hooks/query.js
  wallets/client/hooks/wallet.js
  wallets/lib/util.js
  wallets/server/resolvers/wallet.js
Labels: ui/ux, wallets

#2416 Replace GIFs with WebP
  components/error-boundary.js
  pages/_error.js
  pages/auth/error.js
  pages/email.js
  pages/offline.js
  public/cowboy-saloon.mp4
  public/cowboy-saloon.webp
  public/crying.gif
  public/crying.webp
  public/double.gif
  public/double.webp
  public/falling.gif
  public/falling.webp
  public/floating.gif
  public/floating.webp
  public/forbidden.gif
  public/forbidden.webp
  public/maze.gif
  public/maze.webp
  public/waiting.gif
  public/waiting.webp
  sw/build.js
Labels: multimedia, performance

#2239 Order carousel as images appear in items / markdown
  components/carousel.js
  components/item-full.js
  components/media-or-link.js
Labels: bug, multimedia

#2377 live comments: comments navigation
  components/comment.js
  components/comment.module.css
  components/comments.js
  components/nav/desktop/top-bar.js
  components/nav/mobile/top-bar.js
  components/nav/sticky-bar.js
  components/use-comments-navigator.js
  components/use-visibility.js
  pages/items/[id]/index.js
Labels: enhancement, ui/ux

#2400 live comments: favicon
  components/favicon.js
  components/nav/common.js
  components/use-comments-navigator.js
  pages/_app.js
  public/favicon-comments.png
  public/favicon-notify-with-comments.png
Labels: enhancement, ui/ux

#2421 live comments: toggle
  components/footer.js
  components/use-live-comments.js
  svgs/chat-off-fill.svg
  svgs/chat-unread-fill.svg
Labels: enhancement, ui/ux

#2454 Change layout in wallet prompt
  wallets/client/hooks/prompt.js
Labels: enhancement, ui/ux, wallets

#2456 Map lnAddr to correct wallet on save via prompt
  wallets/client/hooks/prompt.js
  wallets/client/hooks/query.js
Labels: feature, wallets

#2472 Improve image detection
  worker/imgproxy.js
Labels: multimedia
