Repository stackernews/stacker.news, pull requests merged in 2025-04, with the labels that each got.

#2053 Replace 'autowithdraw' in wallet subtitle
  wallets/cln/index.js
  wallets/lightning-address/index.js
  wallets/lnd/index.js
Labels: wallets

#2050 Fix FAQ hydration error
  lib/rehype-sn.js
Labels: bug, documentation

#2054 Remove mention of autowithdrawal for lnaddr
  wallets/lightning-address/index.js
Labels: wallets

#2056 external lightning address validator
  lib/validate.js
  wallets/lightning-address/index.js
Labels: wallets

#2002 Wallet indicators
  components/nav/common.js
  components/nav/mobile/offcanvas.js
  components/wallet-indicator.js
  pages/wallets/index.js
  wallets/index.js
Labels: enhancement, ui/ux, wallets

#2035 System logger for users
  api/paidAction/receive.js
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/wallet-logger.js
  pages/api/lnurlp/[username]/pay.js
  prisma/migrations/20250327192628_system_logger/migration.sql
  prisma/schema.prisma
Labels: ui/ux, wallets

#2041 Update NDK to v2.12.2
  lib/nostr.js
  package-lock.json
  package.json
  scripts/test-nip57.sh
  wallets/nwc/client.js
  wallets/nwc/index.js
Labels: bug, auth

#2062 Fix NWC recv
  wallets/nwc/server.js
Labels: bug, wallets

#2063 Verify testCreateInvoice returns a payment request
  api/resolvers/wallet.js
Labels: bug, wallets

#2065 Fix wrong method in error message
  lib/cln.js
  lib/url.js
  wallets/blink/common.js
  wallets/lightning-address/server.js
  wallets/lnbits/client.js
  wallets/lnbits/server.js
  wallets/phoenixd/client.js
  wallets/phoenixd/server.js
Labels: bug, wallets

#2040 Wallet badges
  api/resolvers/notifications.js
  api/resolvers/user.js
  api/typeDefs/notifications.js
  api/typeDefs/user.js
  components/badge.js
  components/notifications.js
  fragments/comments.js
  fragments/items.js
  fragments/notifications.js
  fragments/subs.js
  fragments/users.js
  lib/apollo.js
  prisma/migrations/20250328203730_wallet_badges/migration.sql
  prisma/schema.prisma
  scripts/newsletter.js
  worker/index.js
  worker/paidAction.js
  worker/streak.js
  worker/thisDay.js
  worker/wallet.js
Labels: ui/ux, wallets

#2088 Use wallets instead of wallets.length as useZap dependency
  components/item-act.js
  wallets/index.js
Labels: bug, wallets

#2089 Handle lightning address JSON errors
  lib/lnurl.js
  lib/url.js
Labels: ui/ux, wallets

#2096 Non-word boundary Regex on user Mentions
  lib/rehype-sn.js
Labels: bug

#2094 enhance: helpful error message on login
  components/login.js
Labels: ui/ux, auth

#2091 Fix wallet indicator blink via wallet loading state
  components/wallet-indicator.js
  pages/wallets/index.js
  wallets/index.js
Labels: bug, ui/ux, wallets

#2097 Fix item deletion hits constraint
  prisma/migrations/20250411220921_fix_item_delete/migration.sql
Labels: bug

#2059 Wallet prompt
  api/resolvers/user.js
  api/typeDefs/user.js
  components/use-item-submit.js
  fragments/users.js
  prisma/migrations/20250402221806_hide_wallet_prompt/migration.sql
  prisma/schema.prisma
  styles/wallet.module.css
  wallets/prompt.js
Labels: feature, ui/ux, wallets

#2071 show sats on full view pinned comments
  components/comment.js
  components/item-info.js
Labels: ui/ux

#2074 Crop avatars with Imgproxy
  .env.development
  api/resolvers/user.js
  api/typeDefs/user.js
  components/avatar.js
  components/user-header.js
  worker/imgproxy.js
Labels: enhancement, multimedia

#2104 Remove unused wallet resolvers
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  fragments/wallet.js
Labels: wallets

#2110 Remove unused vault resolvers
  api/resolvers/vault.js
  api/typeDefs/vault.js
  fragments/vault.js
Labels: wallets

#2118 Fix push notifications sent without thread subscription
  lib/webPush.js
Labels: bug

#2120 Also unsubscribe from any children
  api/resolvers/item.js
  components/subscribe.js
Labels: ui/ux

#2123 Fix push notification sent without own thread subscription
  lib/webPush.js
Labels: bug

#2128 Mention "phantom reads" in README
  api/paidAction/README.md
Labels: documentation

#2130 Close every relay in every pool
  lib/nostr.js
Labels: bug, wallets

#2134 Fix privacy setting interfering with wallet prompt
  api/resolvers/user.js
  api/typeDefs/user.js
Labels: bug, wallets

#2138 Fix lnaddr attach fails if minSendable > 1000
  wallets/lightning-address/server.js
Labels: bug, wallets

#2139 Fix missing method in lnurlp error
  lib/lnurl.js
Labels: wallets

#2140 Fix error message on content-type mismatch
  lib/url.js
Labels: bug, wallets
