Repository stackernews/stacker.news, pull requests merged in 2025-01, with the labels that each got.

#1784 Fix ignored cancel error
  components/use-qr-payment.js
Labels: bug

#1786 collapse childless deleted comments
  components/comment.js
Labels: enhancement

#1787 Allow cancel of own invoices without hmac
  api/resolvers/wallet.js
  api/typeDefs/wallet.js
  components/use-invoice.js
  fragments/wallet.js
Labels: enhancement, wallets

#1788 Fix expirein used instead of keepuntil
  api/paidAction/boost.js
  api/paidAction/index.js
  api/paidAction/itemCreate.js
  api/paidAction/itemUpdate.js
  api/paidAction/lib/item.js
  prisma/migrations/20250103011357_fix_expireboost_keepuntil/migration.sql
Labels: bug

#1789 Fix insecure default id for invites
  prisma/migrations/20250103150109_fix_invite_cuid_insecure/migration.sql
  prisma/schema.prisma
Labels: bug

#1798 Fix scroll after modal close
  components/modal.js
Labels: bug, ux

#1796 fix: iOS notification counts and sums are wacky
  components/serviceworker.js
  sw/eventListener.js
Labels: bug

#1811 Fix job edits
  api/resolvers/item.js
Labels: bug

#1805 Use sats / ccs format in item details
  components/item-info.js
  components/item.module.css
Labels: enhancement, ux

#1799 Add FAQ to version control
  docs/dev/generating-seed.md
  docs/dev/semantic-search.md
  docs/dev/time-is-a-bitch.md
  docs/dev/useful-dev-commands.md
  docs/user/faq.md
  scripts/deploy_user_documentation.js
Labels: documentation, feature

#1823 Update forward limits
  wallets/wrap.js
Labels: bug

#1828 Fix typo in CC info
  components/info/cc.js
Labels: bug

#1831 Remove msats warning
  wallets/server.js
Labels: wallets

#1814 fix: globally pinned items rank in global
  api/resolvers/item.js
Labels: bug

#1820 fix: duplicate push notification on subscribed user and territory
  lib/webPush.js
Labels: bug

#1829 Fix recent sort order for retried items
  api/resolvers/item.js
  api/typeDefs/item.js
  components/item-info.js
  fragments/comments.js
  fragments/items.js
  prisma/migrations/20250122114228_recent_sort_by_invoice_paid_at/migration.sql
  prisma/schema.prisma
Labels: bug

#1839 Subscribe unarchiver to unarchived territory
  api/paidAction/territoryUnarchive.js
Labels: bug, enhancement

#1841 fix: allow downzapping of pinned posts
  components/item-info.js
Labels: bug

#1843 Fix missing push notifications for thread subscriptions
  api/paidAction/itemCreate.js
  lib/webPush.js
Labels: bug

#1842 FAQ formatting changes
  docs/user/faq.md
Labels: documentation

#1847 Add createrune info for v24.11
  wallets/cln/index.js
Labels: bug, documentation

#1840 fix: Images on iOS are cropped weird
  components/media-or-link.js
Labels: bug
